"""create honey chain schema

Revision ID: d4ea2836b701
Revises: 
Create Date: 2026-09-04 20:29:46.079032
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd4ea2836b701'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_code', sa.String(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_finalized AND finalized_at IS NOT NULL) OR (NOT is_finalized AND finalized_at IS NULL)', name='ck_collection_lots_finalization_consistency'),
    sa.CheckConstraint('quantity_kg > 0', name='ck_collection_lots_quantity_kg_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'BEEKEEPER', 'PROCESSOR', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_actor_user_id', 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_events_entity_type_entity_id', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_events_timestamp', 'audit_events', ['timestamp'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_code', sa.String(), nullable=False),
    sa.Column('processor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'HOLD', 'RECALL', name='batch_status'), server_default='ACTIVE', nullable=False),
    sa.Column('is_finalized', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_finalized AND finalized_at IS NOT NULL) OR (NOT is_finalized AND finalized_at IS NULL)', name='ck_batches_finalization_consistency'),
    sa.ForeignKeyConstraint(['processor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_code')
    )
    op.create_table('harvests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('harvest_code', sa.String(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_finalized AND finalized_at IS NOT NULL) OR (NOT is_finalized AND finalized_at IS NULL)', name='ck_harvests_finalization_consistency'),
    sa.CheckConstraint('quantity_kg > 0', name='ck_harvests_quantity_kg_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('harvest_code')
    )
    op.create_table('hives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hive_code', sa.String(), nullable=False),
    sa.Column('beekeeper_id', sa.UUID(), nullable=False),
    sa.Column('location_region', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='hive_status'), server_default='ACTIVE', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beekeeper_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hive_code')
    )
    op.create_table('batch_collection_lots',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('collection_lot_id', sa.UUID(), nullable=False),
    sa.Column('quantity_used_kg', sa.Numeric(), nullable=False),
    sa.CheckConstraint('quantity_used_kg > 0', name='ck_batch_collection_lots_quantity_used_kg_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['collection_lot_id'], ['collection_lots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('batch_id', 'collection_lot_id')
    )
    op.create_index('ix_batch_collection_lots_collection_lot_id', 'batch_collection_lots', ['collection_lot_id'], unique=False)
    op.create_table('collection_lot_harvests',
    sa.Column('collection_lot_id', sa.UUID(), nullable=False),
    sa.Column('harvest_id', sa.UUID(), nullable=False),
    sa.Column('quantity_used_kg', sa.Numeric(), nullable=False),
    sa.CheckConstraint('quantity_used_kg > 0', name='ck_collection_lot_harvests_quantity_used_kg_positive'),
    sa.ForeignKeyConstraint(['collection_lot_id'], ['collection_lots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('collection_lot_id', 'harvest_id')
    )
    op.create_index('ix_collection_lot_harvests_harvest_id', 'collection_lot_harvests', ['harvest_id'], unique=False)
    op.create_table('hive_harvests',
    sa.Column('hive_id', sa.UUID(), nullable=False),
    sa.Column('harvest_id', sa.UUID(), nullable=False),
    sa.Column('quantity_used_kg', sa.Numeric(), nullable=False),
    sa.CheckConstraint('quantity_used_kg > 0', name='ck_hive_harvests_quantity_used_kg_positive'),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('hive_id', 'harvest_id')
    )
    op.create_table('lab_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('certificate_id', sa.String(), nullable=False),
    sa.Column('test_summary', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', 'REVOKED', name='lab_evidence_status'), server_default='ACTIVE', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_id')
    )
    op.create_table('packaging_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_lot_code', sa.String(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('BOTTLES', 'JARS', 'PACKS', 'POUCHES', name='packaging_unit'), nullable=False),
    sa.Column('package_size_grams', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('package_size_grams > 0', name='ck_packaging_lots_package_size_grams_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_packaging_lots_quantity_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_lot_code')
    )
    op.create_table('telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hive_id', sa.UUID(), nullable=False),
    sa.Column('device_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(), nullable=False),
    sa.Column('humidity_pct', sa.Numeric(), nullable=False),
    sa.Column('quality', sa.Enum('VALID', 'SUSPECT', 'INVALID', name='telemetry_quality'), nullable=False),
    sa.CheckConstraint('humidity_pct <= 100', name='ck_telemetry_humidity_pct_maximum'),
    sa.CheckConstraint('humidity_pct >= 0', name='ck_telemetry_humidity_pct_nonnegative'),
    sa.CheckConstraint('weight_kg >= 0', name='ck_telemetry_weight_kg_nonnegative'),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telemetry_hive_id_device_timestamp', 'telemetry', ['hive_id', 'device_timestamp'], unique=False)
    op.create_table('blockchain_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('lab_evidence_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='blockchain_status'), server_default='PENDING', nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('block_number', sa.BIGINT(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lab_evidence_id'], ['lab_evidence.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('packaging_lot_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='qr_status'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['packaging_lot_id'], ['packaging_lots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('packaging_lot_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hive_id', sa.UUID(), nullable=False),
    sa.Column('telemetry_id', sa.UUID(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_score', sa.Numeric(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('AI_MODEL', 'RULE_ENGINE', 'HYBRID', name='risk_source'), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 1', name='ck_risk_events_score_range'),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['telemetry_id'], ['telemetry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_events_hive_id_evaluated_at', 'risk_events', ['hive_id', 'evaluated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_events_hive_id_evaluated_at', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_table('qr_tokens')
    op.drop_table('blockchain_records')
    op.drop_index('ix_telemetry_hive_id_device_timestamp', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_table('packaging_lots')
    op.drop_table('lab_evidence')
    op.drop_table('hive_harvests')
    op.drop_index('ix_collection_lot_harvests_harvest_id', table_name='collection_lot_harvests')
    op.drop_table('collection_lot_harvests')
    op.drop_index('ix_batch_collection_lots_collection_lot_id', table_name='batch_collection_lots')
    op.drop_table('batch_collection_lots')
    op.drop_table('hives')
    op.drop_table('harvests')
    op.drop_table('batches')
    op.drop_index('ix_audit_events_timestamp', table_name='audit_events')
    op.drop_index('ix_audit_events_entity_type_entity_id', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_user_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('collection_lots')
    # ### end Alembic commands ###
